In [1]:
#matrix multiplication
import numpy as nbr
a=nbr.array([[1,2,3],[4,5,6],[7,8,9]])
b=nbr.array([[4,5,6],[5,7,8],[7,8,9]])
print("matrix a:\n",a)
print("matrix b:\n",b)
c=nbr.dot(a,b)
print("matrix multiplication:\n",c)
d=nbr.transpose(c)
print("transpose:\n",d)

matrix a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix b:
 [[4 5 6]
 [5 7 8]
 [7 8 9]]
matrix multiplication:
 [[ 35  43  49]
 [ 83 103 118]
 [131 163 187]]
transpose:
 [[ 35  83 131]
 [ 43 103 163]
 [ 49 118 187]]


In [2]:
a=nbr.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
a=nbr.zeros([3,3],dtype='i')
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
