In [2]:
#program to perform svd
import numpy as nbr
from scipy.linalg import svd
b=nbr.array([[4,5,6],[5,7,8],[7,8,9]])
v,s,t=svd(b)
print(v)
print(s)
print(t)
e=(v @ nbr.diag(s) @t)
print(e)

[[-0.43411677 -0.17898559 -0.88289682]
 [-0.58068705 -0.69368545  0.4261491 ]
 [-0.68872722  0.69768522  0.19720587]]
[20.20715285  0.79770676  0.18611135]
[[-0.46820019 -0.58124027 -0.66554364]
 [ 0.87679704 -0.21216361 -0.43152469]
 [-0.10961539  0.78558663 -0.60896479]]
[[4. 5. 6.]
 [5. 7. 8.]
 [7. 8. 9.]]
